url: https://tedxamstelveen.com
static-url: https://tedxamstelveen.com
baseurl:

# Site settings
title: TEDxAmstelveen
name: TEDxAmstelveen
domain-name: tedxamstelveen.com
robots: INDEX,FOLLOW
email: hallo@tedxamstelveen.com
description: TEDx Amstelveen - 16 Maart 2018 - Thema 'Verbinding'
google_analytics: UA-108379881-1
fb_app_id: 144786006139437
logo: /img/logos/TEDx_Amstelveen-logo.svg
image: /img/logos/TEDx_Amstelveen-horz-white.jpg
author: Ray Bogman

social:
  - title: twitter
    url: https://twitter.com/tedxamstelveen
  - title: facebook
    url: https://www.facebook.com/tedxamstelveen
  - title: youtube
    url: https://www.youtube.com/channel/UCEmelQhyVjPdN07V286mt6g

# Build settings
exclude: [vendor]
markdown: kramdown
permalink: pretty
sass:
    style: compressed
compress_html:
  clippings: all
  endings: all
kramdown:
    enable_coderay: false
    coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

sitemap:
  lastmod: 2017-08-23
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - html-proofer
